version: '2'

services:
 db:
  image: postgres
  expose:
   - "5432"
  volumes:
   - donut-data:/var/lib/postgresql/data/donut
  environment:
   - PGDATA=/var/lib/postgresql/data/donut

 app:
  build: ./app
  links:
    - db
  depends_on:
    - db
  ports:
    - "2154:5000"

volumes:
  donut-data:
   driver: local